import * as esbuild from "esbuild";

const externals = [
  "better-sqlite3",
  "bindings",
  "file-uri-to-path",
  "chokidar",
  "zod",
  "@types/better-sqlite3",
  "@types/chokidar",
  "fs",
  "path",
  "os",
  "url",
  "util",
  "crypto",
  "readline",
  "stream",
  "events",
  "child_process",
  "http",
  "https",
  "assert",
  "buffer",
  "process",
  "module",
  "inspector",
  "perf_hooks",
  "node:fs",
  "node:path",
  "node:os",
  "node:url",
  "node:util",
  "node:crypto",
  "node:readline",
  "node:stream",
  "node:events",
  "node:ChildProcess",
  "node:http",
  "node:https",
  "node:assert",
  "node:buffer",
  "node:process",
  "node:module",
  "node:inspector",
  "node:perf_hooks",
  "node:fs/promises",
  "node:readline/promises",
  "node:stream/promises",
  "@mariozechner/jiti",
  "@mariozechner/clipboard",
  "@mariozechner/mini-lit",
  "@silvia-odwyer/photon-node",
  "undici",
  "ajv",
  "ajv-formats",
  "chalk",
  "cli-highlight",
  "diff",
  "extract-zip",
  "file-type",
  "glob",
  "hosted-git-info",
  "ignore",
  "marked",
  "minimatch",
  "proper-lockfile",
  "strip-ansi",
  "yaml",
  "chokidar",
  "events",
  "readdirp",
  "fill-range",
  "to-regex-range",
  "is-number",
  "is-glob",
  "is-extglob",
  "glob-parent",
  "braces",
  "picomatch",
  "anymatch",
  "normalize-path",
];

await esbuild.build({
  entryPoints: ["./dist/cli.js"],
  bundle: true,
  platform: "node",
  outfile: "./dist/pio",
  format: "esm",
  external: externals,
  logLevel: "warning",
});

console.log("Built: dist/pi");